# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eWallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'IQKeyboardManagerSwift'
  pod 'NVActivityIndicatorView'

  # Pods for eWallet

  target 'eWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eWalletUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
